DEM_PATH: DEM_clip_5m-rpglobal.tif
GML_PATH: MUC_classificacio.gml

TURBINES:
  - id: "YA3"
    x: 347327
    y: 4598444
    lat: 41.52286141
    lon: 1.170478
    elev_platform_m: 2.0
    hub_height_m: 112.0
    rotor_diam_m: 172.0
    solidity: 0.485
    cut_in_ms: 3.0
    cut_out_ms: 25.0
    model: "N175/6.0x"
    rated_power_MW: 6.23
    LwA_octave_dB: [91.8, 98.6, 102.0, 102.5, 103.4, 101.3, 92.0, 75.5]
  - id: "Y09"
    x: 348363
    y: 4598715
    lat: 41.525559
    lon: 1.182837
    elev_platform_m: 2.0
    hub_height_m: 112.0
    rotor_diam_m: 172.0
    solidity: 0.485
    cut_in_ms: 3.0
    cut_out_ms: 25.0
    model: "N175/6.0x"
    rated_power_MW: 6.23
    LwA_octave_dB: [91.8, 98.6, 102.0, 102.5, 103.4, 101.3, 92.0, 75.5]
  - id: "Y05"
    x: 348718
    y: 4598000
    lat: 41.519005
    lon: 1.186957
    elev_platform_m: 2.0
    hub_height_m: 112.0
    rotor_diam_m: 172.0
    solidity: 0.485
    cut_in_ms: 3.0
    cut_out_ms: 25.0
    model: "N175/6.0x"
    rated_power_MW: 6.23
    LwA_octave_dB: [91.8, 98.6, 102.0, 102.5, 103.4, 101.3, 92.0, 75.5]
  - id: "Y06"
    x: 349377
    y: 4597537
    lat: 41.515277
    lon: 1.194854
    elev_platform_m: 2.0
    hub_height_m: 112.0
    rotor_diam_m: 172.0
    solidity: 0.485
    cut_in_ms: 3.0
    cut_out_ms: 25.0
    model: "N175/6.0x"
    rated_power_MW: 6.23
    LwA_octave_dB: [91.8, 98.6, 102.0, 102.5, 103.4, 101.3, 92.0, 75.5]
  - id: "Y07"
    x: 350011
    y: 4597190
    lat: 41.512064
    lon: 1.202922
    elev_platform_m: 2.0
    hub_height_m: 112.0
    rotor_diam_m: 172.0
    solidity: 0.485
    cut_in_ms: 3.0
    cut_out_ms: 25.0
    model: "N175/6.0x"
    rated_power_MW: 6.23
    LwA_octave_dB: [91.8, 98.6, 102.0, 102.5, 103.4, 101.3, 92.0, 75.5]
  - id: "Y8B"
    x: 350526
    y: 4596948
    lat: 41.510136
    lon: 1.209102
    elev_platform_m: 2.0
    hub_height_m: 112.0
    rotor_diam_m: 172.0
    solidity: 0.485
    cut_in_ms: 3.0
    cut_out_ms: 25.0
    model: "N175/6.0x"
    rated_power_MW: 6.23
    LwA_octave_dB: [91.8, 98.6, 102.0, 102.5, 103.4, 101.3, 92.0, 75.5]
    
RECEIVERS:
  La Pobla de Ferran:
    pre:
      Ld: 40.5
      Le: 40.5
      Ln: 45.6
    points:
      -
        id: LPF-1
        x: 349013
        y: 4599960
        h_rec: 4.0
        facade_db: 3.0
        ambient:
          Ld: 41.0
          Le: 41.0
          Ln: 46.0
  Passanant:
    pre:
      Ld: 46.1
      Le: 46.1
      Ln: 32.7
    points:
      -
        id: PAS-1
        x: 349782
        y: 4599406
        h_rec: 4.0
        facade_db: 3.0
        ambient:
          Ld: 55.0
          Le: 53.0
          Ln: 49.0
      -
        id: PAS-2
        x: 349455
        y: 4599284
        h_rec: 4.0
        facade_db: 3.0
        ambient:
          Ld: 63.0
          Le: 63.0
          Ln: 37.0
      -
        id: PAS-3
        x: 349455
        y: 4599284
        h_rec: 4.0
        facade_db: 3.0
        ambient:
          Ld: 47.0
          Le: 47.0
          Ln: 33.0
  Glorieta:
    pre:
      Ld: 41.9
      Le: 41.9
      Ln: 52.5
    points:
      -
        id: GLO-1
        x: 350214
        y: 4597975
        h_rec: 4.0
        facade_db: 3.0
        ambient:
          Ld: 42.0
          Le: 42.0
          Ln: 53.0
      -
        id: GLO-2
        x: 350170
        y: 4597975
        h_rec: 4.0
        facade_db: 3.0
        ambient:
          Ld: 52.0
          Le: 50.0
          Ln: 49.0
  La Sala de Comalats:
    pre:
      Ld: 45.4
      Le: 45.4
      Ln: 57.4
    points:
      -
        id: LSC-1
        x: 351251
        y: 4597853
        h_rec: 4.0
        facade_db: 3.0
        ambient:
          Ld: 46.0
          Le: 46.0
          Ln: 58.0
      -
        id: LSC-2
        x: 351251
        y: 4597853
        h_rec: 4.0
        facade_db: 3.0
        ambient:
          Ld: 53.0
          Le: 52.0
          Ln: 51.0
  Belltall:
    pre:
      Ld: 51.3
      Le: 51.3
      Ln: 59.1
    points:
      -
        id: BEL-1
        x: 348485
        y: 4596665
        h_rec: 4.0
        facade_db: 3.0
        ambient:
          Ld: 52.0
          Le: 52.0
          Ln: 60.0
      -
        id: BEL-2
        x: 348656
        y: 4596434
        h_rec: 4.0
        facade_db: 3.0
        ambient:
          Ld: 55.0
          Le: 52.0
          Ln: 49.0
          
P_FAV:
  Ld: 0.3
  Le: 0.45
  Ln: 0.6
  
TEMP_XEMA:
  DJF: 6.0
  MAM: 12.0
  JJA: 22.0
  SON: 14.0
  
HR_LOCUS:
  DJF: 78.0
  MAM: 68.0
  JJA: 58.0
  SON: 72.0

# Ponderacions estacionals CNOSSOS
W_SEASON:
  Ld:
    DJF: 0.25
    MAM: 0.25
    JJA: 0.30
    SON: 0.20
  Le:
    DJF: 0.25
    MAM: 0.25
    JJA: 0.25
    SON: 0.25
  Ln:
    DJF: 0.30
    MAM: 0.25
    JJA: 0.20
    SON: 0.25


TOL_M: 1.0
N_PROF_PER_KM: 60

GROUND_GS: 0.0   # sòl dur (prop de la turbina)
GROUND_GM: 0.6   # sòl mixt
GROUND_GR: 0.2   # sòl tou 0.8; sòl mixt: 0.5 (prop del receptor); sòl dur, habitatges a tocar d’asfalt, roca, carrers, etc.: 0.0 a 0.4

# ----------------------- PERFILS METEO (Sta. Coloma XEMA per T; bellcam per HR) -----------------------
PRESS_KPA: 97.0  # ~500 a 800 m
TEMP_INVTERM: 4.0 # Tenim molta inversió tèrmica a Passanant, Forès i els inverns són cada vegada menys freds...
TEMP_CANVI: 0.0 # A l'estiu les temperatures apujen cada vegada més...

H_RECEIVER: 4.0  # m (altura general)
FACANA_DB: 3.0   # +3 dB a façana

XMIN: 344500
YMIN: 4595500 
XMAX: 353500 
YMAX: 4600500

RADIUS_NORM_CAT: 500.0
RADIUS_NORM_ESP: 1000.0

LOS_MAX_DIST: 2000.0 # Dibuixar LOS tant sols si distancia inferior a 1200m
GRID_STEP_M: 15.0  # 10.0 costa molt computar, per damunt de 25.0 no és suficent... (més fi, més cost)


# --- Performance
USE_MULTIPROC: true
NUM_CORES: auto   # auto = usa get_optimal_workers(); o posa un enter en funció del hardware: 2,4,8...
USE_NUMBA: true   # si habilites els kernels numèrics (LOS/difracció) amb Numba

# --- Límits d'immissió sonora (Lden) per categoria d'ús del sòl ---
# Cada clau defineix un "perfil" amb [Ld, Le, Ln] (en dB(A))

LIMITS_SETS:
  Sens_55: [55.0, 50.0, 45.0]
  Sens_60: [60.0, 60.0, 50.0]   # Nou perfil (zones urbanes sensibles)
  Sens_65:  [65.0, 60.0, 55.0]

